# @package _global_
dataset:
  batch_size: 16
  num_workers: 8
  prefetch_factor: 2
  sequence_length: 20
  
  # Data paths - UPDATE THESE TO YOUR DATA LOCATIONS
  train_data_path: "/Users/kanis/DLoc_datasets/jacobs_July_100/all_files.csv"
  val_data_path: "/Users/kanis/DLoc_datasets/jacobs_July_100/all_files.csv"
  test_data_path: "/Users/kanis/DLoc_datasets/jacobs_July_100/all_files.csv"
  
  # Number of access points
  train_n_aps: 4
  val_n_aps: 4
  test_n_aps: 4

